service: basic 

plugins:
  - serverless-ruby-layer

provider:
  name: aws
  runtime: ruby2.5

custom:
  rubyLayer:
    exclude_functions:
      - hello3

functions:
  hello1:
    handler: handler1.hello

  hello2:
    handler: handler2.hello

  hello3:
    handler: handler3.hello