service: use-docker-file-with-build-args

plugins:
  - serverless-ruby-layer

custom:
  rubyLayer:
    use_docker: true
    docker_file: Dockerfile
    native_libs:
      - /var/task/test_arg_dummy
      - /var/task/test_arg_present
    docker_build_args:
      - SERVERLESS_RUBY_LAYER_TEST_ARG=test-value

provider:
  name: aws
  runtime: ruby2.5

functions:
  hello:
    handler: handler.hello
