service: use-docker-with-env-passthrough

plugins:
  - serverless-ruby-layer

custom:
  rubyLayer:
    use_docker: true
    docker_env_variable:
      - SERVERLESS_RUBY_LAYER_TEST_ARG

provider:
  name: aws
  runtime: ruby2.5

functions:
  hello:
    handler: handler.hello
