service: use-docker-ignore-gemfile-lock

plugins:
  - serverless-ruby-layer
custom:
  rubyLayer:
    use_docker: true
    ignore_gemfile_lock: true

provider:
  name: aws
  runtime: ruby2.5

functions:
  hello:
    handler: handler.hello
